### ISSUE TITLE
error: command 'gcc' failed: No such file or directory

### ISSUE THREAD

**Issue by emmatyping** [develer-staff/gccwinbinaries#3]
I know in the FAQ it says this should be solved by allowing the installer to change the PATH, but I did, and I am still getting `error: command 'gcc' failed: No such file or directory`.

And yes, I did close and re-open my command prompt.

Why would this happen?

**Comment by emmatyping** [comment]
Never mind, apparently my PATH wasn't included in the way I started CMD. GCC in my path.

**Comment by mshaheerm** [comment]
which path shall be included as i have included but i am still having this error..
